name: Build and push Docker image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set release date
        run: |
          echo "RELEASE_DATE=$(date +%y.%m.%d)" >> ${GITHUB_ENV}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SAVEBOT_TOKEN }}
      -
        name: Owner names
        run: |
          GITOWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          echo "GITOWNER=$GITOWNER" >> ${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/arm/v7,linux/arm/v8
          push: true
          tags: |
            ghcr.io/${{ env.GITOWNER }}/savebot:latest
            ghcr.io/${{ env.GITOWNER }}/savebot:${{ env.RELEASE_DATE }}
            ${{ secrets.DOCKERHUB_USERNAME }}/savebot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/savebot:${{ env.RELEASE_DATE }}
